### ISSUE TITLE
vscode + PlatformIO环境中编译coloview.ino，会提示声明冲突。

### ISSUE THREAD

**Issue by sakunamary** [DFRobot/DFRobot_TCS34725#1]
具体错误如下：

.pio\libdeps\d1_mini\DFRobot_TCS34725\DFRobot_TCS34725.cpp:14:14: error: 'float powf(float, float)' was declared 'extern' and later 'static' [-fpermissive]
   14 | static float powf(const float x, const float y)
      |              ^~~~

**Comment by qsjhyy** [comment]
Hello, our library has been tested based on the Arduino IDE development environment. You can check if the environment you are compiling in already has the powf function. You can try modifying the name of powf in DFRobot_TCS34725.cpp to avoid this issue.

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
