### ISSUE TITLE
Uno WiFi rev2

### ISSUE THREAD

**Issue by samuelkl** [DFRobot/DFRobot_TCS34725#2]
I would like to use your library on my Arduino WiFi rev2 and even though I can find the sensor using an I2C scan, the library doesn't find it.

**Comment by qsjhyy** [comment]
Perhaps you need to provide more detailed problem description, such as trying to debug and print the internal workings of the begin function.
![image](https://github.com/DFRobot/DFRobot_TCS34725/assets/78136558/41a89f8e-1ebf-415b-b841-7685e7e1f62a)

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
